SandroShera
exadelsandbox2022feb/main pull request #14
Opened 2022-01-31 17:10 UTC by SandroShera

2022-01-31 17:12 UTC, apfpo approved these changes

2022-01-31 17:14 UTC, khamza85 requested changes
The file should be under /tmp folder. It also should be named with your github username.

2022-01-31 18:43 UTC, anvar-git approved these changes

2022-02-01 04:44 UTC, apfpo approved these changes

2022-02-01 05:49 UTC, Andrei-Ha requested changes
Sandro, it must be done according  to the 'issue': "Create a file under /tmp folder using your github username as a file name. The file should contain one line text with your email."
Fix please

2022-02-01 10:03 UTC, khamza85 commented
Please, close this PR as a duplicate of #16

2022-02-01 10:06 UTC, closed without merging