Vacation and User endpoints
exadelsandbox2022feb/main pull request #54
Opened 2022-02-10 15:24 UTC by Andrei-Ha

closed #35

2022-02-10 17:11 UTC, khamza85 requested changes
`IResult` and `Results.` types are specific to the minimal API, while for MVC there are `IActionResult` and protected methods from `ControllerBase`. You may want to need to stick with MVC ones.

2022-02-11 11:46 UTC, khamza85 approved these changes

2022-02-11 16:32 UTC, SandroShera approved these changes

2022-02-11 16:32 UTC, Bazilis approved these changes

2022-02-11 16:32 UTC, merged