Telegram api deployment
exadelsandbox2022feb/main pull request #57
Opened 2022-02-12 09:40 UTC by SandroShera

Closes #53

2022-02-12 14:09 UTC, Andrei-Ha approved these changes

2022-02-14 08:26 UTC, khamza85 requested changes
You have some whitespacing issues in your yaml files.

https://github.com/exadelsandbox2022feb/main/actions/runs/1833624721/workflow

2022-02-14 10:35 UTC, khamza85 commented on .github/workflows/telegram-api-deploy.yml
> +  publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
mind indentation

2022-02-14 10:38 UTC, khamza85 requested changes
Fix indentation according to yaml rules. Otherwise https://github.com/exadelsandbox2022feb/main/actions/workflows/telegram-api-deploy.yml will keep failing

2022-02-14 11:52 UTC, khamza85 approved these changes

2022-02-14 12:40 UTC, Bazilis approved these changes

2022-02-14 12:40 UTC, merged